#pragma config(Sensor, S1,     Sound,          sensorSoundDB)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 int clapcounter = 0;
	while(true)
	{
		displayTextLine(2, "Noot Noot LightSwitch");
		displayBigTextLine(4, "Sound: %d", SensorValue (Sound));
		displayBigTextLine(6, "Claps: %d", clapcounter);
		displayBigTextLine(8, "MotorSpeed: %d", motor (motorA));
		setSoundVolume (10);
		playSound (soundLowBuzz);
		if (SensorValue (Sound) >= 70)
		{
			clapcounter = clapcounter + 1;
			wait1Msec (200);
			clearTimer (timer1);
		}
		while (clapcounter >= 2)
		{
			motor (motorA) = 50;
			displayBigTextLine(9, "MotorSpeed: %d", motor (motorA));
			if (getMotorEncoder (motorA) >= 180)
			{
				motor (motorA) = 0;
				displayBigTextLine(9, "MotorSpeed: %d", motor (motorA));
				clapcounter = 0;
				resetMotorEncoder (motorA);
			}
		}
		if (clapcounter >= 1)
		{

			if (getTimerValue (timer1) >= 1000)
			{
				clapcounter = 0;
				clearTimer (timer1);
			}
		}
	}
}
